### ISSUE TITLE
Goban maintener

### ISSUE THREAD

**Issue by Sagebati** [korintje/JerryGo-wasm#1]
Hey,

I saw you just forked my project `Goban` and I saw your cool project. I saw that maybe my API was a little awkward to use.
Buit there is some improvements you can do

`Game::builder()` is the same than GameBuilder::default()
and I saw you iterate on the go_strings. maybe `game.goban().raw()` is less awkward to use.

For any questions don't hesitate, and sorry if I bothered you. If you want some improvements in the library open an issue or PR :).

**Comment by korintje** [comment]
Thanks for opening the issue. I appreciate you to create this cool crate.
Honestly, I am a new at Rust (and Git system and culture, also), so now enjoying study to make my code "rusty".

According to your helpful suggestion, I will fix the two points below:
- Replace `GameBuilder::default()` with `Game::builder()`. 
- Use `game.goban().raw()` instead of iterating go_strings.

I am planning to make a bit modification to the forked `goban` crate like below:
- Record the history of stone moves in the format of SGF.
- Implement `game.move_backward()` and `game.move_forward()`. 

After summarizing my idea, I will open an issue or PR :).

Many thanks!

**Comment by Sagebati** [comment]
Keep up the good work ! 

That's a nice idea ! You can or I will implement https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html to `Game`

**Comment by Sagebati** [comment]
I don't know if it what you need but you can already do this. 

```rust
{
            let mut iter_history = g.history().iter();
            println!("{:?}", iter_history.next().unwrap());
            println!("{:?}", iter_history.next_back().unwrap())
}
```
note before today it was `g.plays().iter()`.

**Comment by korintje** [comment]
Thanks for the kind suggestion!
What I want is quite near to what you told me, but a little different.

I am planning to make a goban which can utilized for examination of the game (Kentou of go).
In other words, I would like to not only view the log of the goban, but also start newly branched game from a certain point. 
For example: 
https://www.cosumi.net/goban.html

I have added some methods to achieve above-mentioned behaviors to my fork project.
I will open pull-request and ask you advice!

**Comment by Sagebati** [comment]
I understand, you want to keep all the variants, could be an awesome PR. I'll looking forward your work !
